source 'https://rubygems.org'

gem 'rails', '~> 5.0.0'

gem 'sqlite3'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'slim-rails'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.5'
gem 'turbolinks', '~> 5.x'

gem 'devise'
gem 'protozaur', github: 'the-teacher/protozaur'

gem 'hold_the_door', path: '../hold_the_door'

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'

  %w[rspec-core rspec-expectations rspec-mocks rspec-rails rspec-support].each do |lib|
    gem lib, git: "https://github.com/rspec/#{lib}.git", branch: 'master'
  end
end

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'pry-rails'
  gem 'ffaker'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
